### ISSUE TITLE
Can this boot Windows To Go?

### ISSUE THREAD

**Issue by kododake** [imbushuo/NintendoSwitchPkg#32]
Hello!
The current problem is that the installer launches but other drivers are not available. can I use a tool such as Rufus to create a Windows To Go and launch Windows directly without using the installer?

**Comment by officialmelon** [comment]
We can currently only use WinPE ATM due to missing drivers. Even then we can't control it what you need is a UART thingy and I think you have to plug it into the switch Controller railing. Then we should be able to control WinPE from a computer with WinDBG. This is what I have learnt from a group of people at least (might be wrong a bit idk)

**Comment by kododake** [comment]
Thank you for your reply.
I am honestly surprised that there are no drivers available for the Switch despite the fact that there are a certain number of ARM Windows devices.
Considering that the Switch supports touch screen and USB in Ubuntu and Android, it seems technically possible, but is it still difficult?
For example, what happens if the Switch driver is installed in advance on Windows To Go and the SD card is loaded on Switch?

**Comment by officialmelon** [comment]
> 

Hey we have a discord server dedicated to the Windows On Nintendo Switch I'm sure the Developers (including me) would love to talk about it there https://discord.gg/jEwzb5T9

**Comment by kododake** [comment]
Thanks for the invite!
I would be happy to talk about it there.

**Comment by thewanderingtraderm** [comment]
the invite link is invalid

**Comment by officialmelon** [comment]
Sorry about that!
https://discord.com/invite/FcqKCZbu
